require 'csv'

CSV.foreach(Rails.root + "db/seeds/countries.csv", :headers => true) do |row|
  c = Country.new(row.to_hash.except('numcode'))
  c.numcode = row['numcode']
  c.save!
end

clubs_regions = {
          'Parkland' => ["Binscarth Curling Club",
                        "Bowsman Curling Club",
                        "Dauphin Curling Club",
                        "Gilbert Plains Curling Club",
                        "Grandview Curling Club",
                        "Roblin Curling Club",
                        "Rorketon Curling Club",
                        "Ste. Rose Curling Club",
                        "Swan River Curling Club"],
          "Central" => ["Altamont Curling Club",
                        "Altona Curling Club",
                        "Baldur Curling Club",
                        "Carman Curling Club",
                        "Cartwright Curling Club",
                        "Clearwater Curling Club",
                        "Cypress River Curling Club",
                        "Elm Creek Curling Club",
                        "Emerson Curling Club",
                        "Gladstone Curling Club",
                        "Halbstadt Curling Club",
                        "Holland Curling Club",
                        "Lansdowne Curling Club",
                        "LaSalle Curling Club",
                        "Manitou Curling Club",
                        "Miami Curling Club",
                        "Morden Curling Club",
                        "Morris Curling Club",
                        "Nor-Mac C.C. (MacGregor)",
                        "Pilot Mound Curling Club",
                        "Plumas Curling Club",
                        "Portage Curling Club",
                        "Roland Curling Club",
                        "St. Claude Curling Club",
                        "St. Jean Curling Club",
                        "St. Leon Curling Club",
                        "Starbuck Curling Club",
                        "Swan Lake Curling Club",
                        "Treherne Curling Club",
                        "Winkler Curling Club"],
        "Interlake" => ["Arborg Curling Club",
                        "Argyle Curling Club",
                        "Balmoral Curling Club",
                        "East St Paul Curling Club",
                        "Eriksdale Curling Club",
                        "Fisher Branch Curling Club",
                        "Gimli Curling Club",
                        "Moosehorn Curling Club",
                        "N. Interlake' (St Martin) Curling Club'",
                        "Petersfield Curling Club",
                        "Riverton Curling Club",
                        "Rosser Curling Club",
                        "Selkirk Curling Club",
                        "Stonewall Curling Club",
                        "Stony Mountain Curling Club",
                        "Teulon Curling Club",
                        "Warren Curling Club",
                        "Winnipeg Beach Curling Club"],
          "Westman" => ["Boissevain Curling Club",
                        "Brandon - Riverview Curling Club",
                        "Brandon Curling Club",
                        "Brookdale Curling Club",
                        "Carberry Curling Club",
                        "Deloraine Curling Club",
                        "Glenboro Curling Club",
                        "Glenora Curling Club",
                        "Hamiota Curling Club",
                        "Hartney Curling Club",
                        "Kenton Curling Club",
                        "Killarney Curling Club",
                        "Melita Curling Club",
                        "Miniota Curling Club",
                        "Minnedosa Curling Club",
                        "Neepawa Curling Club",
                        "Newdale Curling Club",
                        "Rapid City Curling Club",
                        "Rivers Curling Club",
                        "Roseland Curling Club",
                        "Shoal Lake Curling Club",
                        "Souris Curling Club",
                        "Virden Curling Club",
                        "Waskada Curling Club",
                        "Wawanesa Curling Club"],
          "Eastman" => ["Beausejour Curling Club",
                        "Bissett Curling Club",
                        "Grand Marais Curling Club",
                        "Lac du Bonnet Curling Club",
                        "Lorette Curling Club",
                        "Pinawa Curling Club",
                        "Pine Falls Curling Club",
                        "Springfield Curling Club",
                        "St. Adolphe Curling Club",
                        "Ste. Anne Curling Club",
                        "Steinbach Curling Club",
                        "Whiteshell Curling Club"],
            "Norman" => ["Flin Flon Curling Club",
                        "Gillam Curling Club",
                        "Norway House Curling Club",
                        "Snow Lake Curling Club",
                        "The Pas Curling Club",
                        "Thompson - Burntwood Curling Club",
                        "Willow Park Curling Club"],
          "Winnipeg" => ["Assiniboine Memorial Curling Club",
                        "Charleswood Curling Club",
                        "Deer Lodge Curling Club",
                        "Elmwood Curling Club",
                        "Fort Garry Curling Club",
                        "Fort Rouge Curling Club",
                        "Granite Curling Club",
                        "Heather Curling Club",
                        "Pembina Curling Club",
                        "Rossmere Country Club",
                        "St. Vital Curling Club",
                        "The Wildewood Curling Club",
                        "Thistle Curling Club",
                        "Victoria Curling Club",
                        "West Kildonan Curling Club",
                        "West St. Paul Curling Club"]
            }

clubs_regions.each do |region, clubs|
  r = Region.create!(:name => region)
  clubs.each {|c| r.clubs.create(:name => c) }
end

